apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: sec-vol
      mountPath: "/etc/creds"
      readOnly: true
  volumes:
  - name: sec-vol
    secret:
      secretName: db-user-pass-48g6g5c4fg 
