apiVersion: v1
kind: Service
metadata:
        name: my-nodeport-service
spec:
        type: NodePort
        ports:
                - port: 8080 #service_port
                  targetPort: 80 #Pod/container port
                  nodePort: 31515 #This range is from 30000 to 32767
        selector:
                app: myapp 
